// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Firplak.Domain.Models
{
    public partial class LogisticaFirplackBDContext : DbContext
    {
        public LogisticaFirplackBDContext()
        {
        }

        public LogisticaFirplackBDContext(DbContextOptions<LogisticaFirplackBDContext> options)
            : base(options)
        {
        }

        public virtual DbSet<AsignacionBodega> AsignacionBodega { get; set; }
        public virtual DbSet<Bodega> Bodega { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Entrega> Entrega { get; set; }
        public virtual DbSet<Fabricacion> Fabricacion { get; set; }
        public virtual DbSet<Factura> Factura { get; set; }
        public virtual DbSet<GuiaTransporte> GuiaTransporte { get; set; }
        public virtual DbSet<Indicadores> Indicadores { get; set; }
        public virtual DbSet<LineaPedido> LineaPedido { get; set; }
        public virtual DbSet<Pedido> Pedido { get; set; }
        public virtual DbSet<PruebaEntrega> PruebaEntrega { get; set; }
        public virtual DbSet<Trazabilidad> Trazabilidad { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<AsignacionBodega>(entity =>
            {
                entity.HasKey(e => e.AsignacionID)
                    .HasName("PK__Asignaci__D82B5BB7AC3D4BE2");

                entity.Property(e => e.AsignacionID).HasDefaultValueSql("(newid())");

                entity.HasOne(d => d.Bodega)
                    .WithMany(p => p.AsignacionBodega)
                    .HasForeignKey(d => d.BodegaID)
                    .HasConstraintName("FK__Asignacio__Bodeg__2F10007B");
            });

            modelBuilder.Entity<Bodega>(entity =>
            {
                entity.Property(e => e.BodegaID).HasDefaultValueSql("(newid())");

                entity.Property(e => e.Nombre).HasMaxLength(255);
            });

            modelBuilder.Entity<Cliente>(entity =>
            {
                entity.Property(e => e.ClienteID).HasDefaultValueSql("(newid())");

                entity.Property(e => e.Direccion).HasMaxLength(255);

                entity.Property(e => e.Nombre).HasMaxLength(255);
            });

            modelBuilder.Entity<Entrega>(entity =>
            {
                entity.Property(e => e.EntregaID).HasDefaultValueSql("(newid())");

                entity.Property(e => e.FechaDespacho).HasColumnType("datetime");

                entity.Property(e => e.FechaEntregaReal).HasColumnType("datetime");

                entity.HasOne(d => d.GuiaTransporte)
                    .WithMany(p => p.Entrega)
                    .HasForeignKey(d => d.GuiaTransporteID)
                    .HasConstraintName("FK__Entrega__GuiaTra__46E78A0C");
            });

            modelBuilder.Entity<Fabricacion>(entity =>
            {
                entity.Property(e => e.FabricacionID).HasDefaultValueSql("(newid())");

                entity.Property(e => e.FechaFabricacion).HasColumnType("datetime");

                entity.HasOne(d => d.LineaPedido)
                    .WithMany(p => p.Fabricacion)
                    .HasForeignKey(d => d.LineaPedidoID)
                    .HasConstraintName("FK__Fabricaci__Linea__4316F928");
            });

            modelBuilder.Entity<Factura>(entity =>
            {
                entity.Property(e => e.FacturaID).HasDefaultValueSql("(newid())");

                entity.Property(e => e.FechaRadicacion).HasColumnType("datetime");

                entity.Property(e => e.Monto).HasColumnType("decimal(18, 2)");

                entity.HasOne(d => d.Cliente)
                    .WithMany(p => p.Factura)
                    .HasForeignKey(d => d.ClienteID)
                    .HasConstraintName("FK__Factura__Cliente__4CA06362");

                entity.HasOne(d => d.Entrega)
                    .WithMany(p => p.Factura)
                    .HasForeignKey(d => d.EntregaID)
                    .HasConstraintName("FK__Factura__Entrega__4BAC3F29");

                entity.HasOne(d => d.GuiaTransporte)
                    .WithMany(p => p.Factura)
                    .HasForeignKey(d => d.GuiaTransporteID)
                    .HasConstraintName("FK__Factura__GuiaTra__4AB81AF0");
            });

            modelBuilder.Entity<GuiaTransporte>(entity =>
            {
                entity.Property(e => e.GuiaTransporteID).HasDefaultValueSql("(newid())");

                entity.Property(e => e.FechaDespacho).HasColumnType("datetime");

                entity.Property(e => e.NumeroGuia).HasMaxLength(255);

                entity.Property(e => e.TipoTransporte).HasMaxLength(255);

                entity.HasOne(d => d.Cliente)
                    .WithMany(p => p.GuiaTransporte)
                    .HasForeignKey(d => d.ClienteID)
                    .HasConstraintName("FK__GuiaTrans__Clien__32E0915F");
            });

            modelBuilder.Entity<Indicadores>(entity =>
            {
                entity.HasKey(e => e.IndicadorID)
                    .HasName("PK__Indicado__D69F5346762C207B");

                entity.Property(e => e.IndicadorID).HasDefaultValueSql("(newid())");

                entity.Property(e => e.Nombre).HasMaxLength(255);

                entity.Property(e => e.Valor).HasColumnType("decimal(18, 2)");
            });

            modelBuilder.Entity<LineaPedido>(entity =>
            {
                entity.Property(e => e.LineaPedidoID).HasDefaultValueSql("(newid())");

                entity.Property(e => e.Estado).HasMaxLength(255);

                entity.Property(e => e.FechaEntrega).HasColumnType("datetime");

                entity.Property(e => e.PrecioUnitario).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.ProductoSKU).HasMaxLength(255);

                entity.Property(e => e.TipoProducto).HasMaxLength(3);

                entity.HasOne(d => d.AsignacionBodega)
                    .WithMany(p => p.LineaPedido)
                    .HasForeignKey(d => d.AsignacionBodegaID)
                    .HasConstraintName("FK__LineaPedi__Asign__3F466844");

                entity.HasOne(d => d.GuiaTransporte)
                    .WithMany(p => p.LineaPedido)
                    .HasForeignKey(d => d.GuiaTransporteID)
                    .HasConstraintName("FK__LineaPedi__GuiaT__3E52440B");

                entity.HasOne(d => d.Pedido)
                    .WithMany(p => p.LineaPedido)
                    .HasForeignKey(d => d.PedidoID)
                    .HasConstraintName("FK__LineaPedi__Pedid__3D5E1FD2");
            });

            modelBuilder.Entity<Pedido>(entity =>
            {
                entity.Property(e => e.PedidoID).HasDefaultValueSql("(newid())");

                entity.Property(e => e.FechaPedido).HasColumnType("datetime");

                entity.HasOne(d => d.Cliente)
                    .WithMany(p => p.Pedido)
                    .HasForeignKey(d => d.ClienteID)
                    .HasConstraintName("FK__Pedido__ClienteI__286302EC");
            });

            modelBuilder.Entity<PruebaEntrega>(entity =>
            {
                entity.Property(e => e.PruebaEntregaID).HasDefaultValueSql("(newid())");

                entity.HasOne(d => d.GuiaTransporte)
                    .WithMany(p => p.PruebaEntrega)
                    .HasForeignKey(d => d.GuiaTransporteID)
                    .HasConstraintName("FK__PruebaEnt__GuiaT__5070F446");
            });

            modelBuilder.Entity<Trazabilidad>(entity =>
            {
                entity.Property(e => e.TrazabilidadID).HasDefaultValueSql("(newid())");

                entity.Property(e => e.Estado).HasMaxLength(255);

                entity.Property(e => e.FechaHora).HasColumnType("datetime");

                entity.Property(e => e.Ubicacion).HasMaxLength(255);

                entity.HasOne(d => d.LineaPedido)
                    .WithMany(p => p.Trazabilidad)
                    .HasForeignKey(d => d.LineaPedidoID)
                    .HasConstraintName("FK__Trazabili__Linea__5441852A");
            });

            OnModelCreatingGeneratedProcedures(modelBuilder);
            OnModelCreatingGeneratedFunctions(modelBuilder);
            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}