// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Firplak.Domain.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Firplak.Domain.Models
{
    public partial class LogisticaFirplackBDContext
    {
        private ILogisticaFirplackBDContextProcedures _procedures;

        public virtual ILogisticaFirplackBDContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new LogisticaFirplackBDContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public ILogisticaFirplackBDContextProcedures GetProcedures()
        {
            return Procedures;
        }

        protected void OnModelCreatingGeneratedProcedures(ModelBuilder modelBuilder)
        {
        }
    }

    public partial class LogisticaFirplackBDContextProcedures : ILogisticaFirplackBDContextProcedures
    {
        private readonly LogisticaFirplackBDContext _context;

        public LogisticaFirplackBDContextProcedures(LogisticaFirplackBDContext context)
        {
            _context = context;
        }
    }
}
